### ISSUE TITLE
Page lists for tags are empty?

### ISSUE THREAD

**Issue by dsteuer** [chollinger93/ink-free#3]
Hi, very nice theme! One question: 
/tags shows a list of tags, as expected, but if there is i.e. "tag1" as tag then
/tags/tag1 does not show a list of pages with "tag1" but jumps back to /tags

Is this intended? Is it curable?

**Comment by chollinger93** [comment]
Should be fixed on the master branch version. Thanks!

**Comment by dsteuer** [comment]
Am Mon, 31 Jan 2022 18:05:02 +0000 (UTC)
schrieb Christian Hollinger ***@***.***>:

> Should be fixed on the master branch version. Thanks!
>

Works, yes, thx!

Detlef
